# Generated by Django 4.0.5 on 2022-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='Occupants_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
