# Generated by Django 4.0.5 on 2022-06-18 16:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_neighbourhood_helpline'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
