# Generated by Django 4.0.5 on 2022-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_neighbourhood_hood_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
