# Generated by Django 4.0.5 on 2022-06-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_neighbourhood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neigborhood', to='app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='Occupants_Count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
