# Generated by Django 4.0.5 on 2022-06-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_neighbourhood_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='user',
        ),
    ]
