# Generated by Django 4.0.5 on 2022-06-19 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_neighbourhood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoods', to=settings.AUTH_USER_MODEL),
        ),
    ]
