# Generated by Django 4.0.5 on 2022-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_business_business_logo_business_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
