# Generated by Django 4.0.5 on 2022-06-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_business_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood_id',
            new_name='neighbourhood',
        ),
    ]
