# Generated by Django 4.0.5 on 2022-06-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_neighbourhood_id_business_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='neighbourhood_id',
        ),
    ]
