# Generated by Django 4.0.5 on 2022-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_neighbourhood_business_neighbourhood_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='helpline',
            new_name='health_helpline',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_helpline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
